services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_local
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ollama serve & 
        sleep 5
        ollama pull llama3.2:3b
        touch /tmp/model_ready
        wait
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/model_ready"]
      interval: 10s
      timeout: 5s
      retries: 30   
      start_period: 15s

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OLLAMA_MODEL=${OLLAMA_MODEL}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
    depends_on:
      mysql_db:
        condition: service_healthy
      ollama:
        condition: service_healthy

  streamer:
    build:
      context: ./streamer
      dockerfile: Dockerfile
    container_name: request_streamer
    depends_on:
      backend:
        condition: service_started

volumes:
  mysql_data:
  ollama_data: